#!/bin/sh
myname=${0##*/}
log() { logger -p user.info -t "${myname}[$$]" "$*"; }
IFACE=$1
ACTION=$2

release=$(lsb_release -s -c)
case ${release} in
    trusty|utopic) nmobj=nm;;
    *) nmobj=radio;;
esac

case ${IFACE} in
    eth*|usb*|en*)
        case ${ACTION} in
		up)
		ISCORRECTWIFI=$(nmcli connection show --active | grep 802-11-wireless | grep -c 'your ssid')
		if [ "$ISCORRECTWIFI" -gt 0 ]; then
               		log "disabling wifi radio"
	                nmcli "${nmobj}" wifi off
		fi
      	        ;;
		down)
                log "enabling wifi radio"
               	nmcli "${nmobj}" wifi on
	        ;;
        esac
	;;
esac

