#!/bin/sh
my_name=${0##*/}
log() { logger -p user.info -t "${my_name}[$$]" "$*"; }
IFACE=$1
ACTION=$2

release=$(lsb_release -s -c)
case ${release} in
    trusty|utopic) nm_object=nm;;
    *) nm_object=radio;;
esac

case ${IFACE} in
    eth*|usb*|en*)
        case ${ACTION} in
		up)
		IS_CORRECT_WIFI=$(nmcli connection show --active | grep 802-11-wireless | grep -c 'your ssid')
		if [ "$IS_CORRECT_WIFI" -gt 0 ]; then
               		log "disabling wifi radio"
	                nmcli "${nm_object}" wifi off
		fi
      	        ;;
		down)
                log "enabling wifi radio"
               	nmcli "${nm_object}" wifi on
	        ;;
        esac
	;;
esac

