#!/bin/bash

set -euo pipefail

CONTAINER=php73
DOCKER_TAG="${CONTAINER}:latest"
PROJECT=$(realpath ~/.project)
NETWORK="$(basename "${PROJECT}" | sed 's/[^a-z-]//')_internal"
DEV=$(realpath ~/.dev)
CURRENT_DIR=$(dirname $0)

source ${CURRENT_DIR}/.php_docker_run
