#!/bin/bash

#set -euxo pipefail

PROJECT=$(file ~/.project | sed 's/.* to //')
DEV=$(file $HOME/$(file ~/.dev | sed 's/.* to //') | sed 's/.* to //')

#docker run --hostname=php73 --volume=$HOME/${DEV}/php7.3/home:/home/honza --volume=/home/honza/prog:/home/honza/prog -it php73:latest -c "cd ${DEV}/php7.3/;${*:-zsh -i}"
docker run --hostname=php73 --volume=$HOME/${DEV}/php7.3/home:/home/honza --volume=/home/honza/prog:/home/honza/prog -it php73:latest -c "cd ${PROJECT};${*:-zsh -i}"
