#!/bin/bash

EVROUTER=`which evrouter`
CONFIG=$HOME/.evrouterrc

if [ "$EVROUTER" = "" ]; then
	echo "no evrouter"
	exit 2
fi
#sudo /bin/chgrp adm /dev/input/event*

FILENAME="/tmp/.evrouter$DISPLAY"

$EVROUTER -q
if [ -f "$FILENAME" ] ; then
	kill $(cat $(echo "$FILENAME" | sed -e 's/\.[0-9]//'))
	sleep 1
	if [ -f "$FILENAME" ] ; then
		rm "$FILENAME"
	fi
fi

DEVICES="/dev/input/event3"
for device in $(sed < "$CONFIG" 's/"[^"]\+" "//;s/".*//' | sort | uniq | grep -vE '^#' | grep usb) ; do
	THIS_DEVICE="/dev/input/by-id/$device"
	if [ -e "$THIS_DEVICE" ]; then
		DEVICES="$DEVICES $THIS_DEVICE"
	fi
done
evrouter -r ${DEVICES} "--config=$CONFIG"


