#!/bin/bash

EVROUTER=`which evrouter`
CONFIG=$HOME/.evrouterrc

if [ "$EVROUTER" = "" ]; then
	echo "no evrouter"
	exit 2
fi
sudo /bin/chgrp adm /dev/input/event*

FILENAME="/tmp/.evrouter$DISPLAY"

$EVROUTER -q
if [ -f "$FILENAME" ] ; then
	kill $(cat $(echo "$FILENAME" | sed -e 's/\.[0-9]//'))
	sleep 1
	if [ -f "$FILENAME" ] ; then
		rm "$FILENAME"
	fi
fi

DEVICES=""
for device in $(sed < "$CONFIG" 's/"[^"]\+" "//;s/".*//' | sort | uniq | grep -vE '^#' | grep usb) ; do
	DEVICES="$DEVICES /dev/input/by-id/$device"
done
evrouter -r ${DEVICES} "--config=$CONFIG"


