#!/bin/sh
#-----------------------------------------------------------------------------
#
#  This is a small wrapper for the osmium binary that is only used to call it
#  from the build directory, ie when it is not installed. It sets the MANPATH
#  so the help facility will work and then calls the osmium proper.
#
#-----------------------------------------------------------------------------

export MANPATH=$MANPATH:/home/honza/Downloads/osm/osmium-tool/build/man:

exec /home/honza/Downloads/osm/osmium-tool/build/src/osmium "$@"

