#!/bin/bash

# PhpStorm URL Handler
# phpstorm://open?url=file://@file&line=@line
# phpstorm://open?file=@file&line=@line
#
# @license GPL
# @author Stefan Auditor <stefan.auditor@erdfisch.de>

arg=${1}
pattern=".*file(:\/\/|\=)(.*)&line=([0-9]+)"

# Get the file path.
file=$(echo "${arg}" | sed -r "s/${pattern}/\2/;s~phpstorm:~~g;s~^/+~~g;s~usr/src/ucrm/~~g" )
project_dir=$(realpath "$(readlink "$HOME/.project")")
file=$(echo "$project_dir/$file" | sed -r "s/&line=.*//;s/open\?file=//" | sed "s~\(${project_dir}\)\{2,\}~\1~")

# Get the line number.
line=$(echo "${arg}" | sed -r "s/${pattern}/\3/")

# Check if phpstorm|pstorm command exist.
if type pstorm > /dev/null; then
    /usr/bin/env pstorm --line "${line}" "${file}"
elif type phpstorm > /dev/null; then
    /usr/bin/env phpstorm --line "${line}" "${file}"
fi

if type activate-ps.sh > /dev/null; then
    /usr/bin/env activate-ps.sh
fi
