#!/bin/bash

which xdotool || exit 3
which Xephyr || exit 2
which evilwm || exit 1

Xephyr -screen 1280x800 :1 &

XDOTOOL_COMMAND="getdisplaygeometry"

sleep 1
export DISPLAY=:1
xdotool $XDOTOOL_COMMAND
if [ "$?" -gt 0 ]; then
	sleep 2
	xdotool $XDOTOOL_COMMAND
	if [ "$?" -gt 0 ]; then
		sleep 4
		xdotool $XDOTOOL_COMMAND
		if [ "$?" -gt 0 ]; then
			exit 4
		fi
	fi
fi
evilwm &


