#!/bin/bash

set -euo pipefail
#set -x

TEMP_FILE="/tmp/${USER}-shellcheck.last"
FILE="$(realpath "${1:-}" 2>/dev/null || true)"
if [[ "$FILE" == "" ]]; then
	FILE="$(cat "$TEMP_FILE")"
	echo "$FILE" >/dev/stderr
fi

[[ ! -e "$FILE" ]] && exit 1

DIFF_FILE="$(mktemp /tmp/scfix.XXXXX.patch)"
(
	cd "$(dirname "$FILE")" || exit
	shfmt -w "$(basename "$FILE")" || true
)

if (shellcheck --shell=bash --format=diff "$FILE" >"$DIFF_FILE" 2>/dev/null); then
	exit 0
else
	if [[ "$(grep -c "^Issues were detected, but none were auto-fixable. Use another format to see them.\$" <"$DIFF_FILE" || true)" -gt 0 ]]; then
		shellcheck --shell=bash --color=always "$FILE"
		exit 1
	else
		patch <"$DIFF_FILE"
	fi
fi
