#!/bin/bash

RUN_AS=honza
RUN_CMD="bash -l -c"

if [ "$USER" != "$RUN_AS" ]; then
    RUN_CMD="sudo su - $RUN_AS -c"
fi
${RUN_CMD} 'Xephyr -ac -screen 1900x1000 -br -reset -terminate 2> /dev/null :10 & (sleep 1 && env -u SESSION_MANAGER -u DBUS_SESSION_BUS_ADDRESS DISPLAY=:10 xfce4-session --display=:10; killall Xephyr)'
