#!/bin/bash

set -euo pipefail
set -x

YTD="$(command -v youtube-dl)"
JQ="$(command -v jq)"
#FFMPEG="$(command -v ffmpeg)"
YTD_OPTIONS=(--restrict-filenames)
PLAYER="$(command -v vlc)"
PLAYER_OPTIONS=(--playlist-enqueue --one-instance)

if [[ -z "${1:-}" ]]; then
  echo "Usage: $0 URL"
  exit 1
fi

if [[ -z "${YTD_DIRECTORY:-}" ]] || [[ ! -d "${YTD_DIRECTORY}/" ]]; then
  YTD_DIRECTORY="${HOME}/Music/downloaded"
fi
if [[ -z "${YTD_METADATA:-}" ]]; then
  YTD_METADATA="${YTD_DIRECTORY}/.metadata"
fi
METADATA_FILE="${YTD_METADATA}/${1//[^a-zA-Z0-9_-]/}.json"

mkdir -p "$YTD_METADATA" && cd "$YTD_DIRECTORY"

if [[ ! -f "$METADATA_FILE" ]]; then
  "${YTD}" "${YTD_OPTIONS[@]}" --yes-playlist --ignore-errors --flat-playlist --dump-json "$@" | "${JQ}" "del(.alt_title)|del(.track)" - >"$METADATA_FILE"
fi
"${YTD}" "${YTD_OPTIONS[@]}" --load-info-json "$METADATA_FILE" --add-metadata --exec "${PLAYER} ${PLAYER_OPTIONS[*]} {}" "$@"
