version: '3.1'

services:
  autossh-tulen:
    image: piskvor-docker-autossh
    restart: always
    volumes:
      - /etc/ssh/autossh/fwd_rsa:/id_rsa
      - /home/honza/.ssh/known_hosts:/known_hosts
    environment:
      - SSH_HOSTUSER=fwd
      - SSH_HOSTNAME=tulen
      - SSH_TUNNEL_REMOTE=16783
      - SSH_TUNNEL_HOST=10.42.0.1
      - SSH_TUNNEL_LOCAL=22
      - SSH_EXTRA_OPTIONS=-vv
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
  dropbox-jan:
    image: janeczku/dropbox
    restart: always
    environment:
      - DBOX_UID=1000
      - DBOX_GID=1000
    volumes:
      - /home/honza/bigdisk/honza/Dropbox:/dbox/Dropbox
      - /home/honza/bigdisk/honza/.dropbox-docker-config:/dbox/.dropbox
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 100M
        reservations:
          memory: 50M
  dropbox-agcz:
    image: janeczku/dropbox
    restart: always
    environment:
      - DBOX_UID=1000
      - DBOX_GID=1000
    volumes:
      - /home/honza/bigdisk/honza/agcz-Dropbox:/dbox/Dropbox
      - /home/honza/bigdisk/honza/.dropbox-docker-config-agcz:/dbox/.dropbox
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 100M
        reservations:
          memory: 50M
