version: '3.1'

services:
  dropbox-jan:
    image: piskvor-docker-dropbox
    restart: always
    environment:
      - DBOX_UID=1000
      - DBOX_GID=1000
    volumes:
      - /home/honza/bigdisk/honza/Dropbox:/dbox/Dropbox
      - /home/honza/bigdisk/honza/.dropbox-docker-config:/dbox/.dropbox
#      - /home/honza/prog/.dropbox-dist:/opt/dropbox
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 200M

  imap:
    # Uncomment this for build image in local
    #build:
    #   context: .
    image: antespi/docker-imap-devel:latest
    restart: always
    #container_name: imap
    ports:
      - "1025:25"
      - "10143:143"
      - "10993:993"
    environment:
      - MAILNAME=example.piskvor.org
      - MAIL_ADDRESS=piskvor@example.piskvor.org
      - MAIL_PASS=hunter2
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 100M
