version: '3.1'

services:
  autossh-tulen:
    image: piskvor-docker-autossh
    restart: always
    volumes:
      - /etc/ssh/autossh/fwd_rsa:/id_rsa:ro
      - /home/honza/.ssh/known_hosts:/known_hosts:ro
      - /home/honza/.ssh/config:/ssh_config:ro
      - /home/honza/.ssh/socks:/socks:rw
    environment:
      - SSH_HOSTUSER=fwd
      - SSH_HOSTNAME=tulen
      - SSH_TUNNEL_REMOTE=16784
      - SSH_TUNNEL_HOST=10.31.4.1
      - SSH_TUNNEL_LOCAL=22
      - SSH_CONTROL_PATH=/socks/fwd@tulen:22
      - SSH_EXTRA_OPTIONS=-v -o ControlMaster=yes -L0.0.0.0:3128:localhost:3128
      - AUTOSSH_LOGLEVEL=2
      - AUTOSSH_FIRST_POLL=120
      - AUTOSSH_GATETIME=0
      - REMOVE_BROKEN_SSHMUX=1
    ports:
      - "13128:3128"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
  autossh-threepio:
    image: piskvor-docker-autossh
    restart: always
    volumes:
      - /etc/ssh/autossh/fwd_rsa:/id_rsa:ro
      - /home/honza/.ssh/known_hosts:/known_hosts:ro
      - /home/honza/.ssh/config:/ssh_config:ro
      - /home/honza/.ssh/socks:/socks:rw
    environment:
      - SSH_HOSTUSER=honza
      - SSH_HOSTNAME=othreepio
      - SSH_TUNNEL_REMOTE=16785
      - SSH_TUNNEL_HOST=10.31.4.1
      - SSH_TUNNEL_LOCAL=22
      - SSH_EXTRA_OPTIONS=-v -o CheckHostIP=no -o ControlMaster=yes -L0.0.0.0:3128:localhost:3128
      - SSH_CONTROL_PATH=/socks/honza@t:443
      - AUTOSSH_LOGLEVEL=2
      - AUTOSSH_FIRST_POLL=120
      - AUTOSSH_GATETIME=0
      - REMOVE_BROKEN_SSHMUX=1
    ports:
      - "13129:3128"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
  dropbox-jan:
    image: janeczku/dropbox
    restart: always
    environment:
      - DBOX_UID=1000
      - DBOX_GID=1000
    volumes:
      - /home/honza/bigdisk/honza/Dropbox:/dbox/Dropbox
      - /home/honza/bigdisk/honza/.dropbox-docker-config:/dbox/.dropbox
#      - /home/honza/prog/.dropbox-dist:/opt/dropbox
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 200M
#  dropbox-agcz:
#    image: janeczku/dropbox
#    restart: always
#    environment:
#      - DBOX_UID=1000
#      - DBOX_GID=1000
#    volumes:
#      - /home/honza/bigdisk/honza/agcz-Dropbox:/dbox/Dropbox
#      - /home/honza/bigdisk/honza/.dropbox-docker-config-agcz:/dbox/.dropbox
##      - /home/honza/prog/.dropbox-dist:/opt/dropbox
#    deploy:
#      resources:
#        limits:
#          cpus: '0.50'
#          memory: 200M
  dropbox-project:
    image: janeczku/dropbox
    environment:
      - DBOX_UID=1000
      - DBOX_GID=1000
    volumes:
      - /home/honza/prog/.project/dropbox:/dbox/Dropbox
      - /home/honza/prog/.project/.dropbox-config:/dbox/.dropbox
      - /home/honza/prog/.project/.dropbox-dist:/opt/dropbox
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 200M
