#! /bin/sh
# Set a new IP address if shared

set -e

# Only run from ifup.
if [ "$MODE" != start ]; then
	exit 0
fi

# We only care about inet. Get ye gone, strange people
# still using ipx.
if [ "$ADDRFAM" != inet ] ; then
	exit 0
fi

# debug print
#env > /root/env.txt

if [ "$IFACE" = eth0 ] || [ "$IFACE" = wlan1 ]; then
    FINAL_OCTET=$(/sbin/ip a | /bin/grep -F "$IFACE" | /bin/grep -F 'inet ' | /bin/grep -Fv 192. | /bin/sed 's~/24 brd.*~~;s~.*inet ~~;s~\([0-9]\+.\)\{3\}~~')
    /sbin/ip addr add 192.168.40.${FINAL_OCTET}/24 dev "$IFACE" || true
    /sbin/ip addr add 192.168.30.${FINAL_OCTET}/24 dev "$IFACE" || true
else
	exit 0
fi

if [ -d /run/systemd/system ]; then
	systemctl restart --no-block tinyproxy.service 2>&1 || true
else
	invoke-rc.d tinyproxy restart 2>&1 || true
fi

exit 0
